name: Build Linux

on:
  workflow_dispatch:
  # push:
  #   branches: [ main ]
  #   paths:
  #     - 'lib/**'
  #     - 'linux/**'
  #     - 'pubspec.yaml'
  # pull_request:
  #   branches: [ main ]
  #   paths:
  #     - 'lib/**'
  #     - 'linux/**'
  #     - 'pubspec.yaml'

jobs:
  build_linux:
    name: Build Linux Desktop
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Enable Linux desktop
        run: flutter config --enable-linux-desktop

      - name: Get dependencies
        run: flutter pub get

      - name: Generate code
        run: flutter packages pub run build_runner build --delete-conflicting-outputs

      - name: Build Linux app
        run: flutter build linux --release

      - name: Create Linux archive
        run: |
          cd build/linux/x64/release/bundle
          tar -czf ../../../../../whaleskin-linux-x64.tar.gz *

      - name: Upload Linux artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-x64
          path: whaleskin-linux-x64.tar.gz
          retention-days: 30
