name: Build All Platforms

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # Этот воркфлоу координирует сборку всех платформ
  # Для отдельной сборки используйте специализированные воркфлоу:
  # - build-android.yml
  # - build-windows.yml  
  # - build-linux.yml
  # - build-web.yml
  
  info:
    name: Build Information
    runs-on: ubuntu-latest
    steps:
      - name: Print build info
        run: |
          echo "🚀 Building WhaleSkin for all platforms"
          echo "📱 Android APK and AAB will be built"
          echo "🖥️ Windows x64 desktop app will be built"
          echo "🐧 Linux x64 desktop app will be built"
          echo "🌐 Web application will be built"
          echo ""
          echo "Use individual workflow files for platform-specific builds:"
          echo "- .github/workflows/build-android.yml"
          echo "- .github/workflows/build-windows.yml"
          echo "- .github/workflows/build-linux.yml"
          echo "- .github/workflows/build-web.yml"

  # Проверка кода перед сборкой
  analyze:
    name: Analyze Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Get dependencies
        run: flutter pub get

      - name: Generate code
        run: flutter packages pub run build_runner build --delete-conflicting-outputs

      - name: Analyze code
        run: flutter analyze

      - name: Check formatting
        run: dart format --set-exit-if-changed lib/
