name: Build Web

on:
  workflow_dispatch:
  # push:
  #   branches: [ main ]
  #   paths:
  #     - 'lib/**'
  #     - 'web/**'
  #     - 'pubspec.yaml'
  # pull_request:
  #   branches: [ main ]
  #   paths:
  #     - 'lib/**'
  #     - 'web/**'
  #     - 'pubspec.yaml'

jobs:
  build_web:
    name: Build Web Application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Enable web
        run: flutter config --enable-web

      - name: Get dependencies
        run: flutter pub get

      - name: Generate code
        run: flutter packages pub run build_runner build --delete-conflicting-outputs

      - name: Build web app
        run: flutter build web --release

      - name: Create web archive
        run: |
          cd build/web
          tar -czf ../../whaleskin-web.tar.gz *

      - name: Upload web artifact
        uses: actions/upload-artifact@v4
        with:
          name: web-build
          path: whaleskin-web.tar.gz
          retention-days: 30

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/web
